// Copyright 2025 Chef Migration Metrics Authors
// SPDX-License-Identifier: Apache-2.0

package datastore

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"
)

// Session represents a row in the sessions table.
type Session struct {
	ID           string
	UserID       string
	Username     string
	AuthProvider string
	Role         string
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

// InsertSessionParams holds the parameters for creating a new session.
type InsertSessionParams struct {
	UserID       string
	Username     string
	AuthProvider string
	Role         string
	ExpiresAt    time.Time
}

// sessionColumns is the SELECT column list for the sessions table.
const sessionColumns = `id, user_id, username, auth_provider, role, expires_at, created_at`

// scanSession scans a single session row into a Session struct.
func scanSession(row interface{ Scan(dest ...any) error }) (Session, error) {
	var s Session
	var userID sql.NullString

	err := row.Scan(
		&s.ID,
		&userID,
		&s.Username,
		&s.AuthProvider,
		&s.Role,
		&s.ExpiresAt,
		&s.CreatedAt,
	)
	if err != nil {
		return Session{}, err
	}
	s.UserID = stringFromNull(userID)
	return s, nil
}

// ---------------------------------------------------------------------------
// CRUD
// ---------------------------------------------------------------------------

// InsertSession creates a new session and returns the created record. The
// session ID (UUID) is generated by the database and doubles as the opaque
// session token.
func (db *DB) InsertSession(ctx context.Context, p InsertSessionParams) (Session, error) {
	query := `
		INSERT INTO sessions (user_id, username, auth_provider, role, expires_at)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING ` + sessionColumns

	row := db.pool.QueryRowContext(ctx, query,
		nullString(p.UserID),
		p.Username,
		p.AuthProvider,
		p.Role,
		p.ExpiresAt,
	)

	s, err := scanSession(row)
	if err != nil {
		return Session{}, fmt.Errorf("datastore: inserting session: %w", err)
	}
	return s, nil
}

// GetSession returns the session with the given ID. Returns ErrNotFound if
// no such session exists.
func (db *DB) GetSession(ctx context.Context, id string) (Session, error) {
	query := `SELECT ` + sessionColumns + ` FROM sessions WHERE id = $1`
	row := db.pool.QueryRowContext(ctx, query, id)

	s, err := scanSession(row)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Session{}, ErrNotFound
		}
		return Session{}, fmt.Errorf("datastore: getting session: %w", err)
	}
	return s, nil
}

// GetValidSession returns the session with the given ID only if it has not
// yet expired. Returns ErrNotFound if the session does not exist or has
// expired.
func (db *DB) GetValidSession(ctx context.Context, id string) (Session, error) {
	query := `SELECT ` + sessionColumns + ` FROM sessions WHERE id = $1 AND expires_at > now()`
	row := db.pool.QueryRowContext(ctx, query, id)

	s, err := scanSession(row)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return Session{}, ErrNotFound
		}
		return Session{}, fmt.Errorf("datastore: getting valid session: %w", err)
	}
	return s, nil
}

// DeleteSession removes a session by ID (explicit logout). Returns
// ErrNotFound if no such session exists.
func (db *DB) DeleteSession(ctx context.Context, id string) error {
	res, err := db.pool.ExecContext(ctx,
		`DELETE FROM sessions WHERE id = $1`, id,
	)
	if err != nil {
		return fmt.Errorf("datastore: deleting session: %w", err)
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// DeleteSessionsByUserID removes all sessions for the given user ID. This is
// useful when locking an account or changing a password.
func (db *DB) DeleteSessionsByUserID(ctx context.Context, userID string) (int, error) {
	res, err := db.pool.ExecContext(ctx,
		`DELETE FROM sessions WHERE user_id = $1`, userID,
	)
	if err != nil {
		return 0, fmt.Errorf("datastore: deleting sessions by user_id: %w", err)
	}
	n, _ := res.RowsAffected()
	return int(n), nil
}

// DeleteSessionsByUsername removes all sessions for the given username. This
// covers both local and externally authenticated sessions.
func (db *DB) DeleteSessionsByUsername(ctx context.Context, username string) (int, error) {
	res, err := db.pool.ExecContext(ctx,
		`DELETE FROM sessions WHERE username = $1`, username,
	)
	if err != nil {
		return 0, fmt.Errorf("datastore: deleting sessions by username: %w", err)
	}
	n, _ := res.RowsAffected()
	return int(n), nil
}

// ---------------------------------------------------------------------------
// Listing
// ---------------------------------------------------------------------------

// ListSessionsByUserID returns all sessions for the given user ID, ordered by
// created_at descending.
func (db *DB) ListSessionsByUserID(ctx context.Context, userID string) ([]Session, error) {
	query := `SELECT ` + sessionColumns + ` FROM sessions WHERE user_id = $1 ORDER BY created_at DESC`
	return db.scanSessions(ctx, query, userID)
}

// CountActiveSessions returns the number of non-expired sessions.
func (db *DB) CountActiveSessions(ctx context.Context) (int, error) {
	var count int
	err := db.pool.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM sessions WHERE expires_at > now()`,
	).Scan(&count)
	if err != nil {
		return 0, fmt.Errorf("datastore: counting active sessions: %w", err)
	}
	return count, nil
}

// scanSessions scans multiple session rows.
func (db *DB) scanSessions(ctx context.Context, query string, args ...any) ([]Session, error) {
	rows, err := db.pool.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("datastore: querying sessions: %w", err)
	}
	defer rows.Close()

	var sessions []Session
	for rows.Next() {
		s, scanErr := scanSession(rows)
		if scanErr != nil {
			return nil, fmt.Errorf("datastore: scanning session row: %w", scanErr)
		}
		sessions = append(sessions, s)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("datastore: iterating session rows: %w", err)
	}
	return sessions, nil
}

// ---------------------------------------------------------------------------
// Cleanup
// ---------------------------------------------------------------------------

// DeleteExpiredSessions removes all sessions whose expires_at is in the past.
// Returns the number of sessions deleted.
func (db *DB) DeleteExpiredSessions(ctx context.Context) (int, error) {
	res, err := db.pool.ExecContext(ctx,
		`DELETE FROM sessions WHERE expires_at <= now()`,
	)
	if err != nil {
		return 0, fmt.Errorf("datastore: deleting expired sessions: %w", err)
	}
	n, _ := res.RowsAffected()
	return int(n), nil
}
