-- =============================================================================
-- Migration 0005: Test Kitchen Extra Columns
-- =============================================================================
-- Adds per-phase output capture (converge_output, verify_output, destroy_output),
-- a timed_out flag, and driver/platform tracking columns to the
-- test_kitchen_results table. The existing process_stdout/process_stderr columns
-- are retained for backward compatibility but the per-phase columns are preferred
-- by the new Test Kitchen runner.
-- =============================================================================

-- Per-phase captured output (stdout+stderr combined per phase).
ALTER TABLE test_kitchen_results
    ADD COLUMN converge_output  TEXT,
    ADD COLUMN verify_output    TEXT,
    ADD COLUMN destroy_output   TEXT;

-- Timeout flag — TRUE when the run was killed due to exceeding the configured
-- timeout. When timed_out is TRUE, converge_passed and tests_passed are FALSE.
ALTER TABLE test_kitchen_results
    ADD COLUMN timed_out BOOLEAN NOT NULL DEFAULT FALSE;

-- Driver and platform tracking. These record what was actually used for the
-- test run, which may differ from the cookbook's .kitchen.yml if overrides
-- were applied.
--
-- driver_used: the Test Kitchen driver name (e.g. 'dokken', 'vagrant', 'ec2').
-- platform_tested: the platform image/box identifier actually used for the run
--   (e.g. 'dokken/ubuntu-22.04', 'bento/centos-8').
-- overrides_applied: TRUE when a .kitchen.local.yml with driver or platform
--   overrides was generated by the application.
ALTER TABLE test_kitchen_results
    ADD COLUMN driver_used        TEXT,
    ADD COLUMN platform_tested    TEXT,
    ADD COLUMN overrides_applied  BOOLEAN NOT NULL DEFAULT FALSE;
