-- Migration 0011: Create config_store table for encrypted configuration storage
--
-- Replaces both the credentials table and runtime_settings table with a
-- unified encrypted key-value store. All values are AES-256-GCM encrypted
-- at the application layer.
--
--specification.

CREATE TABLE IF NOT EXISTS config_store (
    key              TEXT        NOT NULL,
    encrypted_value  BYTEA       NOT NULL,
    nonce            BYTEA       NOT NULL,
    secret           BOOLEAN     NOT NULL DEFAULT false,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by       TEXT        NOT NULL DEFAULT '',

    PRIMARY KEY (key)
);

COMMENT ON TABLE config_store IS
    'Encrypted configuration store. All values are AES-256-GCM encrypted. Replaces credentials and runtime_settings tables.';
COMMENT ON COLUMN config_store.key IS
    'Dot-notation config key (e.g. organisations, collection, credentials/my-key).';
COMMENT ON COLUMN config_store.encrypted_value IS
    'AES-256-GCM encrypted JSON value. Decrypted at the application layer using CMM_CREDENTIAL_ENCRYPTION_KEY.';
COMMENT ON COLUMN config_store.nonce IS
    '12-byte GCM nonce (IV). Unique per write, generated by the application.';
COMMENT ON COLUMN config_store.secret IS
    'When true, the API never returns the decrypted value (write-only). Used for credentials.';
COMMENT ON COLUMN config_store.updated_by IS
    'Username of the admin who last modified this entry.';

-- Index on key prefix to support efficient ListByPrefix queries (e.g. credentials/%).
CREATE INDEX idx_config_store_key_prefix ON config_store USING btree (key text_pattern_ops);
