// Copyright 2025 Chef Migration Metrics Authors
// SPDX-License-Identifier: Apache-2.0

package nodekitchen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/trickyearlobe-chef/chef-migration-metrics/internal/analysis"
	"github.com/trickyearlobe-chef/chef-migration-metrics/internal/config"
)

// KitchenGenConfig holds all parameters needed to generate the kitchen config files.
type KitchenGenConfig struct {
	NodeName          string
	PlatformName      string          // e.g. "centos-7" — the node's OS
	PlatformVersion   string          // e.g. "7.9"
	RunList           []string        // ordered, fully expanded run_list (recipe format)
	TargetChefVersion string          // e.g. "18.4.2"
	CustomAttributes  json.RawMessage // optional node attributes
	HasRoles          bool            // whether roles/ directory is populated
}

// GenerateKitchenYML produces the contents of a .kitchen.yml for a node kitchen run.
func GenerateKitchenYML(cfg KitchenGenConfig) (string, error) {
	if cfg.NodeName == "" {
		return "", fmt.Errorf("nodekitchen: NodeName is required")
	}
	if cfg.PlatformName == "" {
		return "", fmt.Errorf("nodekitchen: PlatformName is required")
	}

	var buf bytes.Buffer
	buf.WriteString("---\n")

	// Driver block.
	buf.WriteString("driver:\n")
	buf.WriteString("  name: dummy\n")

	// Provisioner block.
	buf.WriteString("\nprovisioner:\n")
	major := chefMajorVersion(cfg.TargetChefVersion)
	if major >= 19 {
		buf.WriteString("  name: chef-ice\n")
	} else {
		buf.WriteString("  name: chef_zero\n")
	}
	if cfg.TargetChefVersion != "" {
		fmt.Fprintf(&buf, "  product_version: %q\n", cfg.TargetChefVersion)
	}
	buf.WriteString("  chef_license: accept\n")
	if cfg.HasRoles {
		buf.WriteString("  roles_path: roles\n")
	}

	// Platforms block.
	platformName := cfg.PlatformName
	if cfg.PlatformVersion != "" {
		platformName = cfg.PlatformName + "-" + cfg.PlatformVersion
	}
	buf.WriteString("\nplatforms:\n")
	fmt.Fprintf(&buf, "  - name: %s\n", platformName)

	// Suites block.
	buf.WriteString("\nsuites:\n")
	fmt.Fprintf(&buf, "  - name: %s\n", cfg.NodeName)
	if len(cfg.RunList) > 0 {
		buf.WriteString("    run_list:\n")
		for _, entry := range cfg.RunList {
			fmt.Fprintf(&buf, "      - %s\n", entry)
		}
	}

	// Custom attributes.
	if len(cfg.CustomAttributes) > 0 && string(cfg.CustomAttributes) != "null" && string(cfg.CustomAttributes) != "{}" {
		var attrs map[string]interface{}
		if err := json.Unmarshal(cfg.CustomAttributes, &attrs); err != nil {
			return "", fmt.Errorf("nodekitchen: unmarshalling custom attributes: %w", err)
		}
		if len(attrs) > 0 {
			buf.WriteString("    attributes:\n")
			writeAttributes(&buf, attrs, 6)
		}
	}

	return buf.String(), nil
}

// GenerateOverlay produces the contents of a .kitchen.local.yml overlay.
// Returns empty string and nil error when no platform match is found.
func GenerateOverlay(tkConfig *config.TestKitchenConfig, platformName string) (string, error) {
	if tkConfig == nil {
		return "", nil
	}

	result := config.MatchPlatform(platformName, tkConfig.PlatformMap)
	if result.Entry == nil {
		return "", nil
	}
	if result.Entry.Skip {
		return "", fmt.Errorf("nodekitchen: platform %q is marked as skipped", platformName)
	}

	imageIndex := buildImageIndex(tkConfig.Images)
	profile := analysis.LookupProfile(tkConfig.Driver, tkConfig.ImageFieldName)

	var buf bytes.Buffer
	buf.WriteString("# .kitchen.local.yml — generated by chef-migration-metrics\n")
	buf.WriteString("# DO NOT EDIT — this file is overwritten on each test run\n")

	hasContent := false

	// --- Driver block ---
	if tkConfig.Driver != "" {
		buf.WriteString("\ndriver:\n")
		fmt.Fprintf(&buf, "  name: %s\n", tkConfig.Driver)
		dsKeys := sortedKeys(tkConfig.DriverSettings)
		for _, k := range dsKeys {
			writeDriverSetting(&buf, k, tkConfig.DriverSettings[k], 2)
		}
		secretKeys := sortedStringKeys(tkConfig.DriverSecrets)
		for _, k := range secretKeys {
			envName := driverSecretEnvVar(k)
			fmt.Fprintf(&buf, "  %s: <%%= ENV['%s'] %%>\n", k, envName)
		}
		hasContent = true
	}

	// --- Platform block ---
	entry := result.Entry
	img, imgOK := imageIndex[entry.Image]
	if imgOK {
		buf.WriteString("\nplatforms:\n")
		fmt.Fprintf(&buf, "  - name: %s\n", entry.KitchenName)
		buf.WriteString("    driver:\n")
		fmt.Fprintf(&buf, "      %s: %s\n", profile.ImageFieldName, yamlScalar(img.ID))
		imgDSKeys := sortedKeys(img.DriverSettings)
		for _, k := range imgDSKeys {
			writeDriverSetting(&buf, k, img.DriverSettings[k], 6)
		}

		// Transport block — prefer platform map entry override, fall back to image.
		transport := img.Transport
		if entry.Transport != nil {
			transport = entry.Transport
		}
		if transport != nil {
			buf.WriteString("    transport:\n")
			if transport.Username != "" {
				fmt.Fprintf(&buf, "      username: %s\n", yamlScalar(transport.Username))
			}
			if transport.PasswordCredential != "" {
				envName := transportPasswordEnvVar(img.Name)
				fmt.Fprintf(&buf, "      password: <%%= ENV['%s'] %%>\n", envName)
			}
			if transport.SSHKeyCredential != "" {
				envName := transportKeyEnvVar(img.Name)
				fmt.Fprintf(&buf, "      ssh_key: <%%= ENV['%s'] %%>\n", envName)
			}
		}
		hasContent = true
	}

	if !hasContent {
		return "", nil
	}
	return buf.String(), nil
}

// WriteKitchenConfigs writes .kitchen.yml and optionally .kitchen.local.yml
// into the specified working directory.
func WriteKitchenConfigs(workDir string, kitchenYML, overlay string) error {
	if err := os.WriteFile(filepath.Join(workDir, ".kitchen.yml"), []byte(kitchenYML), 0644); err != nil {
		return fmt.Errorf("nodekitchen: writing .kitchen.yml: %w", err)
	}
	if overlay != "" {
		if err := os.WriteFile(filepath.Join(workDir, ".kitchen.local.yml"), []byte(overlay), 0644); err != nil {
			return fmt.Errorf("nodekitchen: writing .kitchen.local.yml: %w", err)
		}
	}
	return nil
}

// FormatRunListEntry formats a RunListEntry as a kitchen run_list string.
func FormatRunListEntry(entry RunListEntry) string {
	switch entry.Type {
	case "role":
		return fmt.Sprintf("role[%s]", entry.Name)
	case "recipe":
		recipe := entry.RecipeName
		if recipe == "" {
			recipe = "default"
		}
		return fmt.Sprintf("recipe[%s::%s]", entry.Name, recipe)
	default:
		return fmt.Sprintf("recipe[%s::default]", entry.Name)
	}
}

// chefMajorVersion parses the major version from a semver string.
// Duplicated from analysis/kitchen.go — it's tiny and avoids a cross-package
// dependency on an unexported function.
func chefMajorVersion(v string) int {
	if idx := strings.IndexByte(v, '.'); idx > 0 {
		n, _ := strconv.Atoi(v[:idx])
		return n
	}
	return 0
}

// buildImageIndex creates a lookup map from image name to ImageEntry.
func buildImageIndex(images []config.ImageEntry) map[string]config.ImageEntry {
	idx := make(map[string]config.ImageEntry, len(images))
	for _, img := range images {
		idx[img.Name] = img
	}
	return idx
}

// yamlScalar returns the value as a YAML-safe scalar, quoting when necessary.
func yamlScalar(v string) string {
	if v == "" {
		return `""`
	}
	special := `:{}[]&*#?|!@` + "`" + `"' `
	for _, ch := range v {
		if strings.ContainsRune(special, ch) {
			return fmt.Sprintf("%q", v)
		}
	}
	return v
}

// writeAttributes writes a map as indented YAML.
func writeAttributes(buf *bytes.Buffer, attrs map[string]interface{}, indent int) {
	prefix := strings.Repeat(" ", indent)
	keys := make([]string, 0, len(attrs))
	for k := range attrs {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		v := attrs[k]
		switch val := v.(type) {
		case map[string]interface{}:
			fmt.Fprintf(buf, "%s%s:\n", prefix, k)
			writeAttributes(buf, val, indent+2)
		default:
			fmt.Fprintf(buf, "%s%s: %s\n", prefix, k, yamlScalar(fmt.Sprintf("%v", v)))
		}
	}
}

// writeDriverSetting writes a single driver setting key/value pair.
func writeDriverSetting(buf *bytes.Buffer, key string, value any, indent int) {
	prefix := strings.Repeat(" ", indent)
	switch v := value.(type) {
	case map[string]any:
		fmt.Fprintf(buf, "%s%s:\n", prefix, key)
		writeAttributes(buf, v, indent+2)
	default:
		fmt.Fprintf(buf, "%s%s: %s\n", prefix, key, yamlScalar(fmt.Sprintf("%v", v)))
	}
}

// normalizeEnvVarSuffix uppercases a string and replaces non-alphanumeric
// characters with underscores.
func normalizeEnvVarSuffix(s string) string {
	s = strings.ToUpper(s)
	var b strings.Builder
	b.Grow(len(s))
	for _, ch := range s {
		switch {
		case ch >= 'A' && ch <= 'Z':
			b.WriteRune(ch)
		case ch >= '0' && ch <= '9':
			b.WriteRune(ch)
		case ch == '_':
			b.WriteRune(ch)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

func driverSecretEnvVar(key string) string {
	return "CMM_TK_SECRET_" + normalizeEnvVarSuffix(key)
}

func transportPasswordEnvVar(imageName string) string {
	return "CMM_TK_TRANSPORT_" + normalizeEnvVarSuffix(imageName)
}

func transportKeyEnvVar(imageName string) string {
	return "CMM_TK_KEY_" + normalizeEnvVarSuffix(imageName)
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedStringKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
