// Copyright 2025 Chef Migration Metrics Authors
// SPDX-License-Identifier: Apache-2.0

package gitkitchen

import (
	"bytes"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/trickyearlobe-chef/chef-migration-metrics/internal/analysis"
	"github.com/trickyearlobe-chef/chef-migration-metrics/internal/config"
	"github.com/trickyearlobe-chef/chef-migration-metrics/internal/hypervisor"
)

// OverlayParams provides context for VM naming in the generated overlay.
type OverlayParams struct {
	PlatformName      string
	TargetChefVersion string
	CookbookName      string // used for VM naming (vcenter)
	SuiteName         string // used for VM naming (vcenter)

	// ExistingPreDestroy holds the cookbook's own lifecycle.pre_destroy
	// entries (raw YAML values: strings or {local|remote: cmd} maps) read
	// from its untouched .kitchen.yml. When the IP-release hook is injected
	// these are preserved and run before it, so the overlay composes with —
	// rather than clobbers — repo-provided hooks for the same phase.
	ExistingPreDestroy []any
}

// generateOverlay produces the contents of a .kitchen.local.yml overlay
// for a git kitchen run. Returns empty string and nil error when no
// platform match is found.
func generateOverlay(tkConfig config.TestKitchenConfig, params OverlayParams) (string, error) {
	platformName := params.PlatformName
	targetChefVersion := params.TargetChefVersion
	result := config.MatchPlatform(platformName, tkConfig.PlatformMap)
	if result.Entry == nil {
		return "", nil
	}
	if result.Entry.Skip {
		return "", fmt.Errorf("gitkitchen: platform %q is marked as skipped", platformName)
	}

	imageIndex := buildImageIndex(tkConfig.Images)
	profile := analysis.LookupProfile(tkConfig.Driver, tkConfig.ImageFieldName)

	var buf bytes.Buffer
	buf.WriteString("# .kitchen.local.yml — generated by chef-migration-metrics\n")
	buf.WriteString("# DO NOT EDIT — this file is overwritten on each test run\n")

	hasContent := false

	// Driver block
	if tkConfig.Driver != "" {
		buf.WriteString("\ndriver:\n")
		fmt.Fprintf(&buf, "  name: %s\n", tkConfig.Driver)
		dsKeys := sortedKeys(tkConfig.DriverSettings)
		for _, k := range dsKeys {
			writeDriverSetting(&buf, k, tkConfig.DriverSettings[k], 2)
		}
		secretKeys := sortedStringKeys(tkConfig.DriverSecrets)
		for _, k := range secretKeys {
			envName := driverSecretEnvVar(k)
			fmt.Fprintf(&buf, "  %s: <%%= ENV['%s'] %%>\n", k, envName)
		}

		// Inject VM naming for orphan sweep compatibility.
		vmPrefix := tkConfig.EffectiveVMNamePrefix()
		switch strings.ToLower(tkConfig.Driver) {
		case "proxmox":
			fmt.Fprintf(&buf, "  vm_name_prefix: \"%s-\"\n", vmPrefix)
		case "vcenter":
			vmName := hypervisor.GenerateVMName(
				vmPrefix, params.CookbookName, params.SuiteName, platformName, time.Now(),
			)
			fmt.Fprintf(&buf, "  vm_name: %s\n", yamlScalar(vmName))
		}

		hasContent = true
	}

	// Platform block
	entry := result.Entry
	img, imgOK := imageIndex[entry.Image]
	if imgOK {
		buf.WriteString("\nplatforms:\n")
		fmt.Fprintf(&buf, "  - name: %s\n", platformName)
		buf.WriteString("    driver:\n")
		fmt.Fprintf(&buf, "      %s: %s\n", profile.ImageFieldName, yamlScalar(img.ID))
		imgDSKeys := sortedKeys(img.DriverSettings)
		for _, k := range imgDSKeys {
			writeDriverSetting(&buf, k, img.DriverSettings[k], 6)
		}

		// Transport block
		transport := img.Transport
		if entry.Transport != nil {
			transport = entry.Transport
		}
		if transport != nil {
			buf.WriteString("    transport:\n")
			if transport.Username != "" {
				fmt.Fprintf(&buf, "      username: %s\n", yamlScalar(transport.Username))
			}
			if transport.PasswordCredential != "" {
				envName := transportPasswordEnvVar(img.Name)
				fmt.Fprintf(&buf, "      password: <%%= ENV['%s'] %%>\n", envName)
			}
			if transport.SSHKeyCredential != "" {
				envName := transportKeyPathEnvVar(img.Name)
				fmt.Fprintf(&buf, "      ssh_key: <%%= ENV['%s'] %%>\n", envName)
			}
		}
		hasContent = true
	}

	// Provisioner block
	major := chefMajorVersion(targetChefVersion)
	bakedIn := imgOK && img.EffectiveInstallMethod() == "baked_in"
	buf.WriteString("\nprovisioner:\n")
	if bakedIn {
		if major >= 19 {
			buf.WriteString("  name: chef-ice\n")
			buf.WriteString("  install_strategy: skip\n")
		} else {
			buf.WriteString("  require_chef_omnibus: false\n")
		}
		if img.ChefClientPath != "" {
			fmt.Fprintf(&buf, "  chef_client_path: %s\n", yamlScalar(img.ChefClientPath))
		}
		if tkConfig.ChefLicenseKeyCredential != "" {
			if major >= 19 {
				buf.WriteString("  chef_license_key: <%= ENV['CMM_TK_CHEF_LICENSE_KEY'] %>\n")
			}
		}
		buf.WriteString("  chef_license: accept\n")
	} else if major >= 19 {
		buf.WriteString("  name: chef-ice\n")
		if targetChefVersion != "" {
			fmt.Fprintf(&buf, "  product_version: %q\n", targetChefVersion)
		}
		if tkConfig.ChefLicenseKeyCredential != "" {
			buf.WriteString("  chef_license_key: <%= ENV['CMM_TK_CHEF_LICENSE_KEY'] %>\n")
		}
		buf.WriteString("  chef_license: accept\n")
	} else {
		buf.WriteString("  require_chef_omnibus: true\n")
		buf.WriteString("  product_name: chef\n")
		if targetChefVersion != "" {
			fmt.Fprintf(&buf, "  product_version: %q\n", targetChefVersion)
		}
		buf.WriteString("  chef_license: accept-no-persist\n")
	}
	hasContent = true

	// IP-release pre_destroy hook (opt-in per image, default off). Best-effort
	// optimisation to return the DHCP lease promptly on teardown — never a
	// correctness requirement, so it must never fail or block a run.
	if imgOK && img.ReleaseIPOnDestroy {
		_, osFamily, _ := analysis.NormalisePlatformName(platformName)
		if cmd := ipReleaseCommand(osFamily); cmd != "" {
			writeLifecycleHook(&buf, params.ExistingPreDestroy, cmd)
		}
	}

	if !hasContent {
		return "", nil
	}
	return buf.String(), nil
}

// linuxIPReleaseCommand returns the DHCP lease back on Linux. It is engineered
// to never fail an otherwise-successful run: it tries the common release
// binaries in turn (tolerating the absent ones), detaches via nohup + `&` so a
// transport severed by the release is not seen as a hook failure, redirects all
// stdio, and forces the outer shell to exit 0 regardless of outcome.
const linuxIPReleaseCommand = `nohup sh -c 'dhclient -r >/dev/null 2>&1 || dhcpcd -k >/dev/null 2>&1 || networkctl renew >/dev/null 2>&1 || nmcli -t networking off >/dev/null 2>&1 || true' >/dev/null 2>&1 </dev/null & exit 0`

// windowsIPReleaseCommand releases the lease on Windows. `start /b` detaches it
// from the WinRM session and `exit /b 0` forces success regardless of outcome.
const windowsIPReleaseCommand = `start /b "" ipconfig /release & exit /b 0`

// ipReleaseCommand returns the remote IP-release command for the given OS
// family, or "" when no command applies. Everything that is not Windows is
// treated as Linux best-effort — the per-image opt-in is the real gate.
func ipReleaseCommand(osFamily string) string {
	if osFamily == "windows" {
		return windowsIPReleaseCommand
	}
	return linuxIPReleaseCommand
}

// writeLifecycleHook emits a lifecycle.pre_destroy block composing any
// repo-provided entries (preserved, run first) with the injected release
// command. Test Kitchen replaces arrays on merge, so the cookbook's own
// pre_destroy commands must be carried forward here rather than clobbered.
func writeLifecycleHook(buf *bytes.Buffer, existing []any, releaseCmd string) {
	items := make([]any, 0, len(existing)+1)
	items = append(items, existing...)
	items = append(items, map[string]any{"remote": releaseCmd})

	marshalled, err := yaml.Marshal(items)
	if err != nil {
		// Never break overlay generation for a best-effort optimisation.
		return
	}

	buf.WriteString("\nlifecycle:\n")
	buf.WriteString("  pre_destroy:\n")
	for _, line := range strings.Split(strings.TrimRight(string(marshalled), "\n"), "\n") {
		if line == "" {
			buf.WriteByte('\n')
			continue
		}
		fmt.Fprintf(buf, "    %s\n", line)
	}
}

// buildImageIndex creates a lookup map from image name to ImageEntry.
func buildImageIndex(images []config.ImageEntry) map[string]config.ImageEntry {
	idx := make(map[string]config.ImageEntry, len(images))
	for _, img := range images {
		idx[img.Name] = img
	}
	return idx
}

// chefMajorVersion parses the major version from a semver string.
func chefMajorVersion(v string) int {
	if idx := strings.IndexByte(v, '.'); idx > 0 {
		n, _ := strconv.Atoi(v[:idx])
		return n
	}
	return 0
}

// yamlScalar returns the value as a YAML-safe scalar, quoting when necessary.
func yamlScalar(v string) string {
	if v == "" {
		return `""`
	}
	special := `:{}[]&*#?|!@` + "`" + `"' `
	for _, ch := range v {
		if strings.ContainsRune(special, ch) {
			return fmt.Sprintf("%q", v)
		}
	}
	return v
}

// writeDriverSetting writes a single driver setting key/value pair.
func writeDriverSetting(buf *bytes.Buffer, key string, value any, indent int) {
	prefix := strings.Repeat(" ", indent)
	switch v := value.(type) {
	case map[string]any:
		fmt.Fprintf(buf, "%s%s:\n", prefix, key)
		writeNestedMap(buf, v, indent+2)
	default:
		fmt.Fprintf(buf, "%s%s: %s\n", prefix, key, yamlScalar(fmt.Sprintf("%v", v)))
	}
}

func writeNestedMap(buf *bytes.Buffer, m map[string]any, indent int) {
	prefix := strings.Repeat(" ", indent)
	keys := sortedKeys(m)
	for _, k := range keys {
		v := m[k]
		switch val := v.(type) {
		case map[string]any:
			fmt.Fprintf(buf, "%s%s:\n", prefix, k)
			writeNestedMap(buf, val, indent+2)
		default:
			fmt.Fprintf(buf, "%s%s: %s\n", prefix, k, yamlScalar(fmt.Sprintf("%v", val)))
		}
	}
}

// normalizeEnvVarSuffix uppercases and replaces non-alphanumeric chars with underscore.
func normalizeEnvVarSuffix(s string) string {
	s = strings.ToUpper(s)
	var b strings.Builder
	b.Grow(len(s))
	for _, ch := range s {
		switch {
		case ch >= 'A' && ch <= 'Z':
			b.WriteRune(ch)
		case ch >= '0' && ch <= '9':
			b.WriteRune(ch)
		case ch == '_':
			b.WriteRune(ch)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

func driverSecretEnvVar(key string) string {
	return "CMM_TK_SECRET_" + normalizeEnvVarSuffix(key)
}

func transportPasswordEnvVar(imageName string) string {
	return "CMM_TK_TRANSPORT_" + normalizeEnvVarSuffix(imageName)
}

func transportKeyPathEnvVar(imageName string) string {
	return "CMM_TK_KEY_PATH_" + normalizeEnvVarSuffix(imageName)
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedStringKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
