// Copyright 2025 Chef Migration Metrics Authors
// SPDX-License-Identifier: Apache-2.0

package gitkitchen

import (
	"bytes"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/trickyearlobe-chef/chef-migration-metrics/internal/analysis"
	"github.com/trickyearlobe-chef/chef-migration-metrics/internal/config"
	"github.com/trickyearlobe-chef/chef-migration-metrics/internal/hypervisor"
)

// OverlayParams provides context for VM naming in the generated overlay.
type OverlayParams struct {
	PlatformName      string
	TargetChefVersion string
	CookbookName      string // used for VM naming (vcenter)
	SuiteName         string // used for VM naming (vcenter)

	// ExistingPreDestroy holds the cookbook's own lifecycle.pre_destroy
	// entries (raw YAML values: strings or {local|remote: cmd} maps) read
	// from its untouched .kitchen.yml. When the IP-release hook is injected
	// these are preserved and run before it, so the overlay composes with —
	// rather than clobbers — repo-provided hooks for the same phase.
	ExistingPreDestroy []any

	// SetupScripts are opt-in customer setup scripts discovered in the repo
	// for this instance's OS family, in deterministic sorted-by-path order.
	// Each body is inlined into a remote: pre_converge lifecycle hook so the
	// cookbook's converge has its prerequisites (e.g. created users). These
	// hooks MUST fail the run on non-zero exit — never skippable.
	SetupScripts []SetupScript
}

// SetupScript is a repo-provided setup script whose body is inlined into a
// remote: pre_converge hook. Path is the repo-relative path (used only for
// deterministic ordering); Body is the verbatim script contents.
type SetupScript struct {
	Path string
	Body string
}

// generateOverlay produces the contents of a .kitchen.local.yml overlay
// for a git kitchen run. Returns empty string and nil error when no
// platform match is found.
func generateOverlay(tkConfig config.TestKitchenConfig, params OverlayParams) (string, error) {
	platformName := params.PlatformName
	targetChefVersion := params.TargetChefVersion
	result := config.MatchPlatform(platformName, tkConfig.PlatformMap)
	if result.Entry == nil {
		return "", nil
	}
	if result.Entry.Skip {
		return "", fmt.Errorf("gitkitchen: platform %q is marked as skipped", platformName)
	}

	imageIndex := buildImageIndex(tkConfig.Images)
	profile := analysis.LookupProfile(tkConfig.Driver, tkConfig.ImageFieldName)

	var buf bytes.Buffer
	buf.WriteString("# .kitchen.local.yml — generated by chef-migration-metrics\n")
	buf.WriteString("# DO NOT EDIT — this file is overwritten on each test run\n")

	hasContent := false

	// Driver block
	if tkConfig.Driver != "" {
		buf.WriteString("\ndriver:\n")
		fmt.Fprintf(&buf, "  name: %s\n", tkConfig.Driver)
		dsKeys := sortedKeys(tkConfig.DriverSettings)
		for _, k := range dsKeys {
			writeDriverSetting(&buf, k, tkConfig.DriverSettings[k], 2)
		}
		secretKeys := sortedStringKeys(tkConfig.DriverSecrets)
		for _, k := range secretKeys {
			envName := driverSecretEnvVar(k)
			fmt.Fprintf(&buf, "  %s: <%%= ENV['%s'] %%>\n", k, envName)
		}

		// Inject VM naming for orphan sweep compatibility.
		vmPrefix := tkConfig.EffectiveVMNamePrefix()
		switch strings.ToLower(tkConfig.Driver) {
		case "proxmox":
			fmt.Fprintf(&buf, "  vm_name_prefix: \"%s-\"\n", vmPrefix)
		case "vcenter":
			vmName := hypervisor.GenerateVMName(
				vmPrefix, params.CookbookName, params.SuiteName, platformName, time.Now(),
			)
			fmt.Fprintf(&buf, "  vm_name: %s\n", yamlScalar(vmName))
		}

		hasContent = true
	}

	// Platform block
	entry := result.Entry
	img, imgOK := imageIndex[entry.Image]
	if imgOK {
		buf.WriteString("\nplatforms:\n")
		fmt.Fprintf(&buf, "  - name: %s\n", platformName)
		buf.WriteString("    driver:\n")
		fmt.Fprintf(&buf, "      %s: %s\n", profile.ImageFieldName, yamlScalar(img.ID))
		imgDSKeys := sortedKeys(img.DriverSettings)
		for _, k := range imgDSKeys {
			writeDriverSetting(&buf, k, img.DriverSettings[k], 6)
		}

		// Transport block
		transport := img.Transport
		if entry.Transport != nil {
			transport = entry.Transport
		}
		if transport != nil {
			buf.WriteString("    transport:\n")
			if transport.Username != "" {
				fmt.Fprintf(&buf, "      username: %s\n", yamlScalar(transport.Username))
			}
			if transport.PasswordCredential != "" {
				envName := transportPasswordEnvVar(img.Name)
				fmt.Fprintf(&buf, "      password: <%%= ENV['%s'] %%>\n", envName)
			}
			if transport.SSHKeyCredential != "" {
				envName := transportKeyPathEnvVar(img.Name)
				fmt.Fprintf(&buf, "      ssh_key: <%%= ENV['%s'] %%>\n", envName)
			}
		}
		hasContent = true
	}

	// Provisioner block
	major := chefMajorVersion(targetChefVersion)
	bakedIn := imgOK && img.EffectiveInstallMethod() == "baked_in"
	buf.WriteString("\nprovisioner:\n")
	if bakedIn {
		if major >= 19 {
			buf.WriteString("  name: chef-ice\n")
			buf.WriteString("  install_strategy: skip\n")
		} else {
			buf.WriteString("  require_chef_omnibus: false\n")
		}
		if img.ChefClientPath != "" {
			fmt.Fprintf(&buf, "  chef_client_path: %s\n", yamlScalar(img.ChefClientPath))
		}
		if tkConfig.ChefLicenseKeyCredential != "" {
			if major >= 19 {
				buf.WriteString("  chef_license_key: <%= ENV['CMM_TK_CHEF_LICENSE_KEY'] %>\n")
			}
		}
		buf.WriteString("  chef_license: accept\n")
	} else if major >= 19 {
		buf.WriteString("  name: chef-ice\n")
		if targetChefVersion != "" {
			fmt.Fprintf(&buf, "  product_version: %q\n", targetChefVersion)
		}
		if tkConfig.ChefLicenseKeyCredential != "" {
			buf.WriteString("  chef_license_key: <%= ENV['CMM_TK_CHEF_LICENSE_KEY'] %>\n")
		}
		buf.WriteString("  chef_license: accept\n")
	} else {
		buf.WriteString("  require_chef_omnibus: true\n")
		buf.WriteString("  product_name: chef\n")
		if targetChefVersion != "" {
			fmt.Fprintf(&buf, "  product_version: %q\n", targetChefVersion)
		}
		buf.WriteString("  chef_license: accept-no-persist\n")
	}
	hasContent = true

	// Lifecycle hooks share a single block: opt-in customer setup scripts in
	// pre_converge (a correctness requirement — must fail the run) and the
	// opt-in, best-effort IP-release command in pre_destroy (must never fail).
	_, osFamily, _ := analysis.NormalisePlatformName(platformName)
	var releaseCmd string
	if imgOK && img.ReleaseIPOnDestroy {
		releaseCmd = ipReleaseCommand(osFamily)
	}
	writeLifecycle(&buf, params.SetupScripts, params.ExistingPreDestroy, releaseCmd, osFamily)

	if !hasContent {
		return "", nil
	}
	return buf.String(), nil
}

// linuxIPReleaseCommand returns the DHCP lease back on Linux. It is engineered
// to never fail an otherwise-successful run: it tries the common release
// binaries in turn (tolerating the absent ones), detaches via nohup + `&` so a
// transport severed by the release is not seen as a hook failure, redirects all
// stdio, and forces the outer shell to exit 0 regardless of outcome.
const linuxIPReleaseCommand = `nohup sh -c 'dhclient -r >/dev/null 2>&1 || dhcpcd -k >/dev/null 2>&1 || networkctl renew >/dev/null 2>&1 || nmcli -t networking off >/dev/null 2>&1 || true' >/dev/null 2>&1 </dev/null & exit 0`

// windowsIPReleaseCommand releases the lease on Windows. `start /b` detaches it
// from the WinRM session and `exit /b 0` forces success regardless of outcome.
const windowsIPReleaseCommand = `start /b "" ipconfig /release & exit /b 0`

// ipReleaseCommand returns the remote IP-release command for the given OS
// family, or "" when no command applies. Everything that is not Windows is
// treated as Linux best-effort — the per-image opt-in is the real gate.
func ipReleaseCommand(osFamily string) string {
	if osFamily == "windows" {
		return windowsIPReleaseCommand
	}
	return linuxIPReleaseCommand
}

// setupHookCommand returns the remote command for a setup-script body. TK runs
// lifecycle hooks as the (non-root) transport user — unlike the sudo-by-default
// provisioner — so a Linux script that creates users/groups is otherwise denied
// (groupadd: cannot lock /etc/group). Linux bodies therefore run under a sudo
// heredoc; passwordless sudo is already required for the chef converge. The body
// is kept verbatim (and readable) inside the heredoc, and a non-zero exit still
// fails the run — no exit-0 swallowing (unlike the best-effort IP-release hook).
// Windows runs over WinRM (typically as Administrator) and is returned unchanged.
func setupHookCommand(body, osFamily string) string {
	if osFamily == "windows" {
		return body
	}
	return "sudo -E bash <<'CMM_SETUP_EOF'\n" + body + "\nCMM_SETUP_EOF"
}

// writeLifecycle emits a single lifecycle: block covering the phases CMM
// owns. Setup scripts (opt-in, repo-provided) are inlined into pre_converge as
// remote: hooks and carry no skippable flag — the cookbook depends on them, so
// a non-zero exit MUST fail the run. The IP-release command and any repo
// pre_destroy hooks compose in pre_destroy (TK replaces arrays on merge, so the
// cookbook's own pre_destroy commands are carried forward, run first). Emits
// nothing when neither phase has content. Phases are written in lifecycle
// order: pre_converge before pre_destroy.
func writeLifecycle(buf *bytes.Buffer, setupScripts []SetupScript, existingPreDestroy []any, releaseCmd, osFamily string) {
	preConverge := make([]any, 0, len(setupScripts))
	for _, s := range setupScripts {
		preConverge = append(preConverge, map[string]any{"remote": setupHookCommand(s.Body, osFamily)})
	}

	preDestroy := make([]any, 0, len(existingPreDestroy)+1)
	preDestroy = append(preDestroy, existingPreDestroy...)
	if releaseCmd != "" {
		preDestroy = append(preDestroy, map[string]any{"remote": releaseCmd})
	}

	if len(preConverge) == 0 && len(preDestroy) == 0 {
		return
	}

	buf.WriteString("\nlifecycle:\n")
	writeLifecyclePhase(buf, "pre_converge", preConverge)
	writeLifecyclePhase(buf, "pre_destroy", preDestroy)
}

// writeLifecyclePhase emits one "  <phase>:" key with its command array,
// indented under the lifecycle: block. yaml.Marshal handles block-scalar
// quoting of multi-line inlined script bodies. Skips empty phases.
func writeLifecyclePhase(buf *bytes.Buffer, phase string, items []any) {
	if len(items) == 0 {
		return
	}
	marshalled, err := yaml.Marshal(items)
	if err != nil {
		return
	}
	fmt.Fprintf(buf, "  %s:\n", phase)
	for _, line := range strings.Split(strings.TrimRight(string(marshalled), "\n"), "\n") {
		if line == "" {
			buf.WriteByte('\n')
			continue
		}
		fmt.Fprintf(buf, "    %s\n", line)
	}
}

// buildImageIndex creates a lookup map from image name to ImageEntry.
func buildImageIndex(images []config.ImageEntry) map[string]config.ImageEntry {
	idx := make(map[string]config.ImageEntry, len(images))
	for _, img := range images {
		idx[img.Name] = img
	}
	return idx
}

// chefMajorVersion parses the major version from a semver string.
func chefMajorVersion(v string) int {
	if idx := strings.IndexByte(v, '.'); idx > 0 {
		n, _ := strconv.Atoi(v[:idx])
		return n
	}
	return 0
}

// yamlScalar returns the value as a YAML-safe scalar, quoting when necessary.
func yamlScalar(v string) string {
	if v == "" {
		return `""`
	}
	special := `:{}[]&*#?|!@` + "`" + `"' `
	for _, ch := range v {
		if strings.ContainsRune(special, ch) {
			return fmt.Sprintf("%q", v)
		}
	}
	return v
}

// writeDriverSetting writes a single driver setting key/value pair.
func writeDriverSetting(buf *bytes.Buffer, key string, value any, indent int) {
	prefix := strings.Repeat(" ", indent)
	switch v := value.(type) {
	case map[string]any:
		fmt.Fprintf(buf, "%s%s:\n", prefix, key)
		writeNestedMap(buf, v, indent+2)
	default:
		fmt.Fprintf(buf, "%s%s: %s\n", prefix, key, yamlScalar(fmt.Sprintf("%v", v)))
	}
}

func writeNestedMap(buf *bytes.Buffer, m map[string]any, indent int) {
	prefix := strings.Repeat(" ", indent)
	keys := sortedKeys(m)
	for _, k := range keys {
		v := m[k]
		switch val := v.(type) {
		case map[string]any:
			fmt.Fprintf(buf, "%s%s:\n", prefix, k)
			writeNestedMap(buf, val, indent+2)
		default:
			fmt.Fprintf(buf, "%s%s: %s\n", prefix, k, yamlScalar(fmt.Sprintf("%v", val)))
		}
	}
}

// normalizeEnvVarSuffix uppercases and replaces non-alphanumeric chars with underscore.
func normalizeEnvVarSuffix(s string) string {
	s = strings.ToUpper(s)
	var b strings.Builder
	b.Grow(len(s))
	for _, ch := range s {
		switch {
		case ch >= 'A' && ch <= 'Z':
			b.WriteRune(ch)
		case ch >= '0' && ch <= '9':
			b.WriteRune(ch)
		case ch == '_':
			b.WriteRune(ch)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}

func driverSecretEnvVar(key string) string {
	return "CMM_TK_SECRET_" + normalizeEnvVarSuffix(key)
}

func transportPasswordEnvVar(imageName string) string {
	return "CMM_TK_TRANSPORT_" + normalizeEnvVarSuffix(imageName)
}

func transportKeyPathEnvVar(imageName string) string {
	return "CMM_TK_KEY_PATH_" + normalizeEnvVarSuffix(imageName)
}

func sortedKeys(m map[string]any) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedStringKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
